name: Bug report
description: Report a bug with the Frost or another theme in this repo
body:
    - type: textarea
      attributes:
          label: Description
          description: Please write a brief description of the bug, including what you expect to happen and what is currently happening.
          placeholder: |
              Feature '...' is not working properly. I expect '...' to happen, but '...' happens instead
      validations:
          required: true

    - type: textarea
      attributes:
          label: Step-by-step reproduction instructions
          description: Please write the steps needed to reproduce the bug.
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet
          description: |
              If possible, please upload a screenshot or screen recording which demonstrates the bug. You can use LIEcap to create a GIF screen recording: https://www.cockos.com/licecap/
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Environment info
          description: |
              Please list what Frost version you are using. If you are also using a Frost child theme, please note that version as well.
          placeholder: |
            - WordPress version, Gutenberg version (if active), and active Theme you are using.
            - Browser(s) are you seeing the problem on.
            - Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.).
      validations:
          required: false

    - type: dropdown
      id: existing
      attributes:
          label: Please confirm that you have searched existing issues in the repo.
          description: You can do this by searching https://github.com/wpengine/themes/issues and making sure the bug is not related to something else.
          multiple: true
          options:
             - 'Yes'
             - 'No'
      validations:
          required: true
